name: LobbySystem
version: '1.0-SNAPSHOT'
main: de.zKinqJustin.lobbySystem.main
api-version: '1.21'
commands:
  warp:
  build:
    description: Toggle build mode for yourself or another player
    usage: /<command> [player]
  permission:
  lobbysystem.build:
    description: Allows toggling build mode for yourself
    default: op
  lobbysystem.build.others:
    description: Allows toggling build mode for other players
    default: op
  setpos1:
    description: Set the first position for the lobby marker
    usage: /<command>
  setpos2:
    description: Set the second position for the lobby marker
    usage: /<command>
  reloadcommanditems:
    description: Reload the command items configuration
    usage: /<command>
  permissions:
    lobbysystem.reloadcommanditems:
      description: Allows reloading the command items configuration
      default: op
